### ISSUE TITLE
Исправить дефолтное время при создании мероприятия.

### ISSUE THREAD

**Issue by Adalyat** [IT61/it61.info#122]
В данный момент дефолтное время указано UTC (Текущее время-3 часа) ([пруф](https://yadi.sk/i/S9jS6uNv3A84uA)), что не совсем корректно. Т.к. это локальное сообщество, то и время следует использовать локальное или привязаться к Московскому (совпадает с локальным).

**Comment by kovalevsky** [comment]
Время по utc,  это конечно печально.
Но я бы предложил указывать какое-то популярное время ивентов, для времени нового мероприятия, 16:00 или что-то подобное. `DateTime.current` всегда придется исправлять, причем, как и часы и минуты (ивент, который стартует на 24 минуте любого часа – это странно :).

**Comment by Adalyat** [comment]
Согласен. Если развивать тему, то думаю было бы удобно в выпадающем списке минут показывать круглые числа - 00, 05, 10, 15 и т.д. Как было сказано, врядли кто-то укажет 16:03 в качестве начала, а вот 16:15, думаю, запросто. Это, например, может быть связано с доступом к помещению и оборудованию.

**Comment by NeverHappened** [comment]
Да, можно

**Comment by vitallium** [comment]
Fixed.
