### ISSUE TITLE
Invalid SSL certificate

### ISSUE THREAD

**Issue by lex111** [IT61/it61.info#283]
![54ca980320](https://user-images.githubusercontent.com/4408379/62974099-20cc4680-be20-11e9-95a9-a990e696dbeb.png)

Может уже в курсе, но мало ли.

cc @vitallium

**Comment by vitallium** [comment]
Да, в курсе. Случилась небольшая заминка с LE. Уже в процессе устранения.

**Comment by lex111** [comment]
Как вижу, уже проблема решена - сайт открывается, поэтому закрываю ишью.

**Comment by vitallium** [comment]
О, это было быстро. Мне сказали, что сроки решения проблемы 24 часа. 👍
